<?php

/**
 * @file
 * Install/uninstall tasks for Justbook Contact module.
 */

/**
 * Implements hook_uninstall().
 */
function justbook_form_uninstall() {
  // Clean up module variables.
  variable_del('authorcontact_desc');
  variable_del('authorcontact_allow_different_name');
  variable_del('authorcontact_bcc');
  variable_del('authorcontact_form_width');
  variable_del('authorcontact_form_height');
  variable_del('authorcontact_block_display_types');
}
